version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    container_name: devops-app
=======
version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    restart: always

